export const RESET_STATE = 'RESET_STATE';
export const SET_LOADER_VISIBILITY = 'SET_LOADER_VISIBILITY';
export const SET_BROWSER_LOCATION = 'SET_BROWSER_LOCATION';
export const SET_APPLICATION_STRUCTURE = 'SET_APPLICATION_STRUCTURE';
export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN';
export const SET_TRANSLATIONS = 'SET_TRANSLATIONS';

export const ADD_ERROR_MSGS = 'ADD_ERROR_MSGS';
export const SET_ERROR_MSGS = 'SET_ERROR_MSGS';
export const CLEAR_SPECIFIED_ERROR_MSGS = 'CLEAR_SPECIFIED_ERROR_MSGS';

export const ADD_SUCCESS_MSGS = 'ADD_SUCCESS_MSGS';
export const SET_SUCCESS_MSGS = 'SET_SUCCESS_MSGS';
export const CLEAR_SPECIFIED_SUCCESS_MSGS = 'CLEAR_SPECIFIED_SUCCESS_MSGS';

export const ADD_INFO_MSGS = 'ADD_INFO_MSGS';
export const SET_INFO_MSGS = 'SET_INFO_MSGS';
export const CLEAR_SPECIFIED_INFO_MSGS = 'CLEAR_SPECIFIED_INFO_MSGS';

export const ADD_WARNING_MSGS = 'ADD_WARNING_MSGS';
export const SET_WARNING_MSGS = 'SET_WARNING_MSGS';
export const CLEAR_SPECIFIED_WARNING_MSGS = 'CLEAR_SPECIFIED_WARNING_MSGS';

export const SET_SCREEN_TRANSITION_ACTIVITY = 'SET_SCREEN_TRANSITION_ACTIVITY';
export const SET_FIELD_VALIDATIONS_VISIBILITY = 'SET_FIELD_VALIDATIONS_VISIBILITY';

export const REFRESH_ALL_FIELDS = 'REFRESH_ALL_FIELDS';